### ISSUE TITLE
Installing manually

### ISSUE THREAD

**Issue by santi-g-s** [Cuberto/bubble-icon-tabbar#1]
Hi,

I tried installing manually by adding the:

- Assets folder
- CBFlashyTabBarController.h
- Classes folder 
- info.plist

into my Xcode project but I get the following error in the console:

Unknown class BubbleTabBarController in Interface Builder file.
Unknown class CBTabBarItem in Interface Builder file.

I'm sorry if this is really obvious

**Comment by askopin** [comment]
Sorry for broken manual, i fixed it.
For manual installation you should add content of folder BubbleTabBar/Classes to your project.
