### ISSUE TITLE
Selected Images not showing, showing only default one.

### ISSUE THREAD

**Issue by NirajCapermint** [Cuberto/bubble-icon-tabbar#15]
I am using this library and working good other than image. The problem is it is not showing selected image as it is original

![Screenshot 2019-08-31 at 2 26 47 PM](https://user-images.githubusercontent.com/41157695/64061640-65672880-cbfb-11e9-9d40-d948b48ffd81.png)

**Comment by askopin** [comment]
thank you for response, check version 0.8.4, i added support of selected images (do not forget to run pod  instal --repo-update)

**Comment by NirajCapermint** [comment]
Thanks. Though it was working in previous version. Let me try newer version

**Comment by NirajCapermint** [comment]
@askopin  Update to new version, now it is showing images like this for the first time.

![Screenshot 2019-08-31 at 4 02 04 PM](https://user-images.githubusercontent.com/41157695/64062765-be898900-cc08-11e9-9c2c-14cad82ab13c.png)

After I select any other tab item than showing correctly. Any idea what could be the wrong?

![Screenshot 2019-08-31 at 4 03 19 PM](https://user-images.githubusercontent.com/41157695/64062778-de20b180-cc08-11e9-86cf-5dfb25b420dd.png)
