### ISSUE TITLE
Unselected images are showing black by default

### ISSUE THREAD

**Issue by NirajCapermint** [Cuberto/bubble-icon-tabbar#16]
Version 0.8.4 

It is showing images for unselected like this for the first time (black color).

![Screenshot 2019-08-31 at 4 02 04 PM](https://user-images.githubusercontent.com/41157695/64062865-fcd37800-cc09-11e9-8d24-e4241e6b4fa4.png)

After I select any other tab item than showing correctly. Any idea what could be the wrong?

![Screenshot 2019-08-31 at 4 03 19 PM](https://user-images.githubusercontent.com/41157695/64062874-065ce000-cc0a-11e9-89a0-9882430e1b93.png)

**Comment by askopin** [comment]
how do you init control? from storyboard or manually?

**Comment by NirajCapermint** [comment]
From storyboard I just assign the class name to tab bar and from code I am using all the things like:

```
let homeVC = self.storyBoard.instantiateViewController(withIdentifier: SCREENNAME.HOME.rawValue) as! HomeVC
homeVC.tabBarItem = UITabBarItem(title: "Chats", image: #imageLiteral(resourceName: "chat_tab.png"), selectedImage: #imageLiteral(resourceName: "chat_tab_sel.png"))
```

```
let tabBarController = BubbleTabBarController()
        tabBarController.viewControllers = [homeVC,roomsVC,storiesVC,profileVC,settingVC]
        tabBarController.tabBar.tintColor = UIColor().tabBarBackgroundColor
        navigationController = UINavigationController(rootViewController: tabBarController)
        navigationController.navigationBar.isHidden = true
        navigationController.navigationBar.barStyle = .black
        navigationController.interactivePopGestureRecognizer?.isEnabled = true
        appDelegate.window?.rootViewController = navigationController
```

**Comment by askopin** [comment]
first of all, update the lib, I fixed rendering mode behaviour - now it respects rendering mode of both selected and unselected images
on the other hand, if you want to use image with original rendering mode, you should do it explicitly by calling method .withRenderingMode(.alwaysOriginal) of UIImage

**Comment by NirajCapermint** [comment]
I am already using latest version of library and regarding your suggestion of using method of UIImage withRenderingMode(.alwaysOriginal), I already tried that way and nothing works.

**Comment by askopin** [comment]
let's check, the latest binary is 0.8.5?
If it is not - pod install --repo-update
If it is - check sample from branch 'test/original-image-sample' it contains one tab with nontemplate image an it works for me

**Comment by NirajCapermint** [comment]
@askopin Yes, 0.8.5

**Comment by askopin** [comment]
@NirajCapermint did you check sample?
