### ISSUE TITLE
Could you make pod for it 

### ISSUE THREAD

**Issue by ahmedsafadii** [Cuberto/bubble-icon-tabbar#2]
Thanks for this library i will use it in the v2 of my app :) https://itunes.apple.com/de/app/summoners-companion-for-lol/id1171905646?mt=8

if possible add it for cocapods <3

**Comment by askopin** [comment]
It's done!
https://cocoapods.org/pods/BubbleTabBar

**Comment by ahmedsafadii** [comment]
[!] Unable to find a specification for `BubbleTabBar`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by ahmedsafadii** [comment]
@askopin

**Comment by askopin** [comment]
@ahmedsafadii just run `pod install --repo-update` as suggested

**Comment by ahmedsafadii** [comment]
@askopin Thanks it's working now <3

**Comment by OskarMG** [comment]
Hi when I try to install the library it throw this error:

[!] CocoaPods could not find compatible versions for pod "BubbleTabBar":
  In Podfile:
    BubbleTabBar (~> 0.8)

Specs satisfying the `BubbleTabBar (~> 0.8)` dependency were found, but they required a higher minimum deployment target.

Some help here please
