### ISSUE TITLE
Can't set tintColor for barItem via Carthage

### ISSUE THREAD

**Issue by akring** [Cuberto/bubble-icon-tabbar#4]
## What I've done:

1. install via Carthage
2. setup TabBarController as README.md said.
3. set my childVC's barItem's class to 'CBTabBarItem' and module as 'BubbleTabBar'

## What's working:

I get the tabBar styled as espect

## What's wrong:

I can't find 'TintColor' in Xcode attributed inspector when I select barItem

**Comment by askopin** [comment]
unfortunately it's apple limitation: [Carthage issue](https://github.com/Carthage/Carthage/issues/335)
Some of possible workarounds: 
set tint color from code
use "user defined attributes"

**Comment by akring** [comment]
OK, got it. Thank you for your reply!
