### ISSUE TITLE
selectedIndex change error

### ISSUE THREAD

**Issue by emirbeytekin** [Cuberto/bubble-icon-tabbar#5]
i can't change selected index in your ViewController sample file.

`2019-02-20 13:14:01.981736+0300 ExampleApp[50402:789561] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Directly modifying a tab bar managed by a tab bar controller is not allowed.'`

**Comment by askopin** [comment]
fixed in 0.8.3
